// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgLQWTiS0AeSjY-HNOArgEKG9W2dzyTyk',
    appId: '1:1063717283410:web:efe25a8d67cbd1a5db618b',
    messagingSenderId: '1063717283410',
    projectId: 'clubnorms-9ff76',
    authDomain: 'clubnorms-9ff76.firebaseapp.com',
    storageBucket: 'clubnorms-9ff76.appspot.com',
    measurementId: 'G-FLYDC5MZHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCELarKBsTMPmkHM5jHuSjEA-5W-zMVKgw',
    appId: '1:1063717283410:android:bc31518c4ba32d7edb618b',
    messagingSenderId: '1063717283410',
    projectId: 'clubnorms-9ff76',
    storageBucket: 'clubnorms-9ff76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtPZTcIT3q6f55eWLrAP6knJjm3xV8xCQ',
    appId: '1:1063717283410:ios:be9f4118fff779eadb618b',
    messagingSenderId: '1063717283410',
    projectId: 'clubnorms-9ff76',
    storageBucket: 'clubnorms-9ff76.appspot.com',
    iosBundleId: 'com.chandra.clubnorms',
  );
}
